function CodeDefine() { 
this.def = new Array();
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:37,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:74,type:"fcn"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_B"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:44,type:"var"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_DW"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:47,type:"var"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_M"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:53,type:"var"};
this.def["rate_scheduler"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:61,type:"fcn"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_step"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:77,type:"fcn"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_initialize"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:808,type:"fcn"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_terminate"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_c.html",line:7653,type:"fcn"};
this.def["B_AcquireAngleAmicSimple_4kHz_M2017b_T"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_h.html",line:139,type:"type"};
this.def["DW_AcquireAngleAmicSimple_4kHz_M2017b_T"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_h.html",line:198,type:"type"};
this.def["ConstP_AcquireAngleAmicSimple_4kHz_M2017b_T"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_h.html",line:1394,type:"type"};
this.def["RT_MODEL_AcquireAngleAmicSimple_4kHz_M2017b_T"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_types_h.html",line:25,type:"type"};
this.def["AcquireAngleAmicSimple_4kHz_M2017b_ConstP"] = {file: "AcquireAngleAmicSimple_4kHz_M2017b_data_c.html",line:25,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:31,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:55,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:66,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:90,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:31,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:55,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:34,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:40,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:52,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:58,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:64,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:70,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:41,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:48,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:55,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:27,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:45,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["s_params"] = {file: "xpcethercatgetstate_c.html",line:37,type:"type"};
this.def["i_works"] = {file: "xpcethercatgetstate_c.html",line:48,type:"type"};
this.def["mdlInitializeSizes"] = {file: "xpcethercatgetstate_c.html",line:57,type:"fcn"};
this.def["mdlInitializeSampleTimes"] = {file: "xpcethercatgetstate_c.html",line:103,type:"fcn"};
this.def["mdlStart"] = {file: "xpcethercatgetstate_c.html",line:119,type:"fcn"};
this.def["mdlOutputs"] = {file: "xpcethercatgetstate_c.html",line:129,type:"fcn"};
this.def["mdlTerminate"] = {file: "xpcethercatgetstate_c.html",line:143,type:"fcn"};
this.def["s_params"] = {file: "xpcethercatpdorx_c.html",line:51,type:"type"};
this.def["i_works"] = {file: "xpcethercatpdorx_c.html",line:71,type:"type"};
this.def["getDataTypeSize"] = {file: "xpcethercatpdorx_c.html",line:95,type:"fcn"};
this.def["copyBitsUnsigned"] = {file: "xpcethercatpdorx_c.html",line:124,type:"fcn"};
this.def["copyBitsSigned"] = {file: "xpcethercatpdorx_c.html",line:164,type:"fcn"};
this.def["msg"] = {file: "xpcethercatpdorx_c.html",line:204,type:"var"};
this.def["msg"] = {file: "xpcethercatpdorx_c.html",line:204,type:"fcn"};
this.def["msg"] = {file: "xpcethercatpdorx_c.html",line:204,type:"fcn"};
this.def["msg"] = {file: "xpcethercatpdorx_c.html",line:204,type:"fcn"};
this.def["msg"] = {file: "xpcethercatpdorx_c.html",line:204,type:"fcn"};
this.def["msg"] = {file: "xpcethercatpdorx_c.html",line:204,type:"fcn"};
this.def["s_params"] = {file: "xpcethercatpdotx_c.html",line:50,type:"type"};
this.def["EC_PT_PROCESS_VAR_INFO"] = {file: "xpcethercatpdotx_c.html",line:63,type:"type"};
this.def["i_works"] = {file: "xpcethercatpdotx_c.html",line:85,type:"type"};
this.def["msg"] = {file: "xpcethercatpdotx_c.html",line:204,type:"var"};
this.def["msg"] = {file: "xpcethercatpdotx_c.html",line:204,type:"fcn"};
this.def["bitCopy"] = {file: "xpcethercatpdotx_c.html",line:130,type:"fcn"};
this.def["bitCopy"] = {file: "xpcethercatpdotx_c.html",line:130,type:"fcn"};
this.def["bitCopy"] = {file: "xpcethercatpdotx_c.html",line:130,type:"fcn"};
this.def["bitCopy"] = {file: "xpcethercatpdotx_c.html",line:130,type:"fcn"};
this.def["txMaxTime"] = {file: "xpcethercatpdotx_c.html",line:297,type:"var"};
this.def["txMaxTime"] = {file: "xpcethercatpdotx_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpcethercatpdotx_c.html",line:297,type:"fcn"};
this.def["s_params"] = {file: "xpcethercatsetstate_c.html",line:38,type:"type"};
this.def["i_works"] = {file: "xpcethercatsetstate_c.html",line:51,type:"type"};
this.def["txMaxTime"] = {file: "xpcethercatsetstate_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpcethercatsetstate_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpcethercatsetstate_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpcethercatsetstate_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpcethercatsetstate_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpctimeinfo_c.html",line:297,type:"var"};
this.def["txMaxTime"] = {file: "xpctimeinfo_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpctimeinfo_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpctimeinfo_c.html",line:297,type:"fcn"};
this.def["txMaxTime"] = {file: "xpctimeinfo_c.html",line:297,type:"fcn"};
this.def["xmlecatArr_0_count"] = {file: "ecat_config_xml_0_c.html",line:1,type:"var"};
this.def["xmlecatArr_0"] = {file: "ecat_config_xml_0_c.html",line:2,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["AcquireAngleAmicSimple_4kHz_M2017b_c.html"] = "../AcquireAngleAmicSimple_4kHz_M2017b.c";
	this.html2Root["AcquireAngleAmicSimple_4kHz_M2017b_c.html"] = "AcquireAngleAmicSimple_4kHz_M2017b_c.html";
	this.html2SrcPath["AcquireAngleAmicSimple_4kHz_M2017b_h.html"] = "../AcquireAngleAmicSimple_4kHz_M2017b.h";
	this.html2Root["AcquireAngleAmicSimple_4kHz_M2017b_h.html"] = "AcquireAngleAmicSimple_4kHz_M2017b_h.html";
	this.html2SrcPath["AcquireAngleAmicSimple_4kHz_M2017b_private_h.html"] = "../AcquireAngleAmicSimple_4kHz_M2017b_private.h";
	this.html2Root["AcquireAngleAmicSimple_4kHz_M2017b_private_h.html"] = "AcquireAngleAmicSimple_4kHz_M2017b_private_h.html";
	this.html2SrcPath["AcquireAngleAmicSimple_4kHz_M2017b_types_h.html"] = "../AcquireAngleAmicSimple_4kHz_M2017b_types.h";
	this.html2Root["AcquireAngleAmicSimple_4kHz_M2017b_types_h.html"] = "AcquireAngleAmicSimple_4kHz_M2017b_types_h.html";
	this.html2SrcPath["AcquireAngleAmicSimple_4kHz_M2017b_data_c.html"] = "../AcquireAngleAmicSimple_4kHz_M2017b_data.c";
	this.html2Root["AcquireAngleAmicSimple_4kHz_M2017b_data_c.html"] = "AcquireAngleAmicSimple_4kHz_M2017b_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["xpcethercatgetstate_c.html"] = "file:///C:/Program%20Files/MATLAB/R2017b/toolbox/rtw/targets/xpc/target/build/xpcblocks/xpcethercatgetstate.c";
	this.html2Root["xpcethercatgetstate_c.html"] = "xpcethercatgetstate_c.html";
	this.html2SrcPath["xpcethercatpdorx_c.html"] = "file:///C:/Program%20Files/MATLAB/R2017b/toolbox/rtw/targets/xpc/target/build/xpcblocks/xpcethercatpdorx.c";
	this.html2Root["xpcethercatpdorx_c.html"] = "xpcethercatpdorx_c.html";
	this.html2SrcPath["xpcethercatpdotx_c.html"] = "file:///C:/Program%20Files/MATLAB/R2017b/toolbox/rtw/targets/xpc/target/build/xpcblocks/xpcethercatpdotx.c";
	this.html2Root["xpcethercatpdotx_c.html"] = "xpcethercatpdotx_c.html";
	this.html2SrcPath["xpcethercatsetstate_c.html"] = "file:///C:/Program%20Files/MATLAB/R2017b/toolbox/rtw/targets/xpc/target/build/xpcblocks/xpcethercatsetstate.c";
	this.html2Root["xpcethercatsetstate_c.html"] = "xpcethercatsetstate_c.html";
	this.html2SrcPath["xpctimeinfo_c.html"] = "file:///C:/Program%20Files/MATLAB/R2017b/toolbox/rtw/targets/xpc/target/build/xpcblocks/xpctimeinfo.c";
	this.html2Root["xpctimeinfo_c.html"] = "xpctimeinfo_c.html";
	this.html2SrcPath["ecat_config_xml_0_c.html"] = "../../ecat_config_xml_0.c";
	this.html2Root["ecat_config_xml_0_c.html"] = "ecat_config_xml_0_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","AcquireAngleAmicSimple_4kHz_M2017b_c.html","AcquireAngleAmicSimple_4kHz_M2017b_h.html","AcquireAngleAmicSimple_4kHz_M2017b_private_h.html","AcquireAngleAmicSimple_4kHz_M2017b_types_h.html","AcquireAngleAmicSimple_4kHz_M2017b_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","xpcethercatgetstate_c.html","xpcethercatpdorx_c.html","xpcethercatpdotx_c.html","xpcethercatsetstate_c.html","xpctimeinfo_c.html","ecat_config_xml_0_c.html"];
